//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPRINT()
        {
            this.USER_STORY = new HashSet<USER_STORY>();
        }
    
        public int SPRINT_ID { get; set; }
        public int BACKLOG_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public Nullable<System.DateTime> STARTING_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_DATE { get; set; }
    
        public virtual BACKLOG BACKLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_STORY> USER_STORY { get; set; }
    }
}
