//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_STORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_STORY()
        {
            this.SCENARIO = new HashSet<SCENARIO>();
            this.TASK = new HashSet<TASK>();
        }
    
        public int STORY_ID { get; set; }
        public int BACKLOG_ID { get; set; }
        public int PROJECT_ID { get; set; }
        public Nullable<int> SPRINT_ID { get; set; }
        public Nullable<int> PRIORITIES { get; set; }
        public string CLIENT_ROLE { get; set; }
        public Nullable<int> ESTIMATION { get; set; }
        public string REASON { get; set; }
        public string FUNCTIONALITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCENARIO> SCENARIO { get; set; }
        public virtual SPRINT SPRINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASK { get; set; }
    }
}
